version: '3'


services:
    login:
      image: php:main
      volumes:
        - ./login/src:/var/www/html
      ports:
        - 80:80
      links:
        - mysql
      depends_on:
        - mysql
    mysql:
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=password
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - PMA_HOST=mysql
      ports:
        - 8083:80
    authentication:
      image: makbn/cc-authentication-service:v2
      ports:
        - 8080:8080
      links:
        - mysql:db_service_host
      environment:
        DB_HOST: mysql
    master:
      image: php:slimi
      volumes:
        - ./master:/var/www/html/slim/public
      ports:
        - 8088:80
      links:
        - mysql
      depends_on:
        - mysql
    fraudDetection:
      image: php:slimi
      volumes:
        - ./fraudDetection:/var/www/html/slim/public
      ports:
        - 8089:80
      links:
        - mysql
      depends_on:
        - mysql
